### ISSUE TITLE
Mention all contributors in the license

### ISSUE THREAD

**Issue by IgelRM** [subdavis/Tusk#11]
Hello again, I noticed the license only mentions Steven Campbell and Brandon Davis. I think we should honor all contributors in the license, @DukeyToo created a list here https://github.com/perfectapi/CKP/pull/175.

**Comment by subdavis** [comment]
> I think we should honor all contributors

I totally agree.  I'll merge perfectapi#175 as soon as the dust settles.

> in the license

I'm not so sure the license is the best place to put that information.  I'm no legal expert, but I've never seen an open source project add the list of contributors to their license file.  There's just no point, since it uses an MIT license, and I don't intend to accept contributions if they are licensed differently.

**Comment by IgelRM** [comment]
I agree, this would probably be too excessive. Maybe you could write something like, "...held by Steven Campbell and contributors."

**Comment by subdavis** [comment]
I've changed my mind on this one.  GitHub already does a really good job of tracking contributors and what they've contributed to via https://github.com/subdavis/Tusk/graphs/contributors and the blame for each file.

We don't really need to put folks in the license since contributors withhold no rights for the code they submit - it will all be under an MIT license provided by the maintainer (me).

Steve Campbell is listed in the license because I inherited this project and its license from him.  When people contributed, he still held the rights to their contributions (under MIT, he also chose to wave all those rights).  We should think about this from a project perspective rather than an individual contribution perspective.
