### ISSUE TITLE
Cannot change Keepass database to use in Dropbox

### ISSUE THREAD

**Issue by frederickjh** [subdavis/Tusk#136]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

I cannot change the password  file to use in Dropbox. A file is selected but when click on it (where it says to click)  I do not get a window to change it but am given a window that shows the name of the current database that was selected by the extension.

![image](https://user-images.githubusercontent.com/864159/38471517-81a4f056-3b72-11e8-922c-d3f8ca82a460.png)

After clicking I get this:

![image](https://user-images.githubusercontent.com/864159/38471520-90a46f5a-3b72-11e8-843d-5a48dbce88c0.png)

This makes the extension unusable except for the database that was originally selected by Tusk.

### Please describe how you think it should change.

Make it possible to change the Keepass database that is used from Dropbox.

### Anything else?
Keepass Tusk  v2018.2.25
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) (Linux)

**Comment by subdavis** [comment]
Thanks for the documentation.

This looks like a problem with your dropbox files rather than tusk.  Any file ending in kdbx that dropbox finds should be present in the Tusk list.  If you have other databases that don't end in kdbx, Tusk won't find them.

If you have other databases that end in kdbx you can't see, check out the troubleshooting guide https://github.com/subdavis/Tusk/wiki/Troubleshooting#no-databases-found-in-google-drive--dropbox--onedrive

**Comment by frederickjh** [comment]
Hi @subdavis, are you saying that the older version 1 **kdb** files are not supported by Task? I only have one **kdbx** file in Dropbox the rest are **kdb** files, so that could be the reason why I cannot select anything else.

**Comment by subdavis** [comment]
Correct, v1 is pretty much defunct now and unsupported in Tusk.

I highly recommend upgrading all your databases to v4 with chacha and argon2.
