### ISSUE TITLE
gdrive shared database opening problem

### ISSUE THREAD

**Issue by Smyl3** [subdavis/Tusk#15]
If I input a shared gdrive database link, it doesn't recognize my master pass for some reason

**Comment by subdavis** [comment]
@Smyl3 - google drive experiences an intermittent bug with direct download links that involves an infinite redirect.  This bug seemed to be solved when I originally wrote the code, but appears to be back.  Because of that bug, I may be forced to remove this feature.  I'm going to avoid that if possible.

Thanks for reporting this bug - it's a known issue, and I realize I've forgotten to document my research on it.

**Comment by subdavis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CKPX issue #15](https://trello.com/c/mnTrDHYD/6-ckpx-issue-15)

**Comment by subdavis** [comment]
Found the problem... https://productforums.google.com/forum/#!topic/drive/Uyq8Rbuo2xU

Solved by either https://plus.google.com/u/0/+JeffLewisSC/posts/FYsnTrmUKdu or putting https://accounts.google.com/ permanently  in the permissions section of the manifest.

**Comment by subdavis** [comment]
@Smyl3 Issue is resolved in version 2017.9.19 via permissions for now.  If we find that people don't like this, we can remove the feature.  Closing.

**Comment by subdavis** [comment]
Reopened...  It started working again when I changed the permissions settings, and now it stopped.  I think this actually worse than I thought.

**Comment by Smyl3** [comment]
Thanks for your effort. In Vivaldi the 3rd party cookies are already enabled at me. I tried to disable cookie and ublock extensions but its the same, just doesn't accept my password when I want to unlock the database.
