### ISSUE TITLE
Tusk does not open using the Hotkey Navigation on Vivaldi 1.15.1147.55 

### ISSUE THREAD

**Issue by BoKKeR** [subdavis/Tusk#217]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
Tusk does not open with the keyboard combination on Vivaldi 1.15.1147.55. I have enabled Hotkey Navigation but it only seems to work in chrome. In vivaldi it wont open the addon.

### Anything else?

I have not tried any past versions of vivaldi with tusk.

**Comment by zmilonas** [comment]
Hello @BoKKeR 

This is a vivaldi bug. Unfortunately in the current state of things there is nothing we can do about it.

Per https://github.com/bitwarden/browser/issues/192 and https://forum.vivaldi.net/topic/8364/keyboard-shortcuts-for-extensions-is-ineffective or https://forum.vivaldi.net/topic/26479/keyboard-shortcuts-on-extension-doesn-t-work/2

> That is a old unsolved bug in Vivaldi with all extensions.
> No know timeline to fix this yet.
> Bug VB-14668	"Extensions' keyboard shortcuts don't work"

I'm closing this for now since no timeline and we can't do anything about it :(
