### ISSUE TITLE
Redirect to entry URL

### ISSUE THREAD

**Issue by fmunch** [subdavis/Tusk#248]
### This issue is a

feature

### Steps to reproduce - current behaviour

The URL of an entry is only used to match a page and an entry, there is no way to go the URL.

### What is the expected behaviour

As @zmilonas suggested in #246 a redirect feature would be appreciated, or any other technical solution to open a URL from the database.

For example adding a button next to "copy" and "autofill" on each entry (and ideally a keyboard shortcut) triggering a redirect in the current tab.

**Comment by zmilonas** [comment]
As for keyboard shortcut it's getting really dense with these and it's hard to find any more unused ones haha. Great suggestion we need to agree on whether another button will fit since we already have TOTP planned.

Also I have some doubts how many users actually have meaningful URLs in their DBs since the clients do URL matching pretty losely a lot of users might have something like https://google.com URL for an entry that is used on https://accounts.google.com/signin/v2/identifier

@subdavis What do you think about such feature?

**Comment by zmilonas** [comment]
@subdavis From what I understand @fmunch is asking for a new button and/or keybaord shortcut for that same action

**Comment by subdavis** [comment]
> The URL of an entry is only used to match a page and an entry, there is no way to go the URL.

> ...or any other technical solution to open a URL from the database.

That's not how I read that line.  Could @fmunch elaborate on whether they mean explicitly a way to do it from the list view, or that the URL in the details view is good enough?

**Comment by fmunch** [comment]
Oh, since I was using keyboard only I never noticed the details page, sorry.

Unless you feel like adding a new keyboard shortcut to the entry list component (to either show the details page or redirect to the link) this page should probably be enough.

BTW, Esc should close the popup.

Thank you!
