### ISSUE TITLE
 [Feature request] Mobile browser extension support

### ISSUE THREAD

**Issue by gynet** [subdavis/Tusk#282]
The Firefox supports its extension natively and Yandex supports chrome extension as well. I tried both of them, they work great for local file uploading and auto filling, but the cloud mode failed to fetch the db file from Dropbox or Google drive. Also, there are some UI polish issues need to be resolved for mobile especially for Firefox Android. It looks promising if tusk can add support for them.

**Comment by subdavis** [comment]
Mobile Firefox will not be supported because mobile Firefox does not provide the necessary API for authentication 

Browser.identity is not available on mobile.  The firefox add-on page for tusk specifically states that mobile will not be supported.

Thanks for your interest.  I recommend raising this issue with Firefox itself, as this is a compatibility problem.

**Comment by subdavis** [comment]
Edit: recommend you try app.keeweb.info for your mobile KeePass needs
