### ISSUE TITLE
Google blocking access to Google Drive

### ISSUE THREAD

**Issue by UniversalFlamingo** [subdavis/Tusk#354]
### Steps to reproduce - current behaviour

Tusk -> Settings -> Manage Databases

Enable `Google Drive`
Select account (I have two Chrome/Google accounts)

I get a popup saying:
`This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.`

### What is the expected behaviour

It should authenticate & let me choose my databases.

#### Additional remarks

Tusk v2024.8.10

#### Environment 

**Operating System:**

- Chromebook / ChromeOS
- Windows 11

**Browser vendor and version:**

Chrome - 127.0.6533.100

**Storage Provider:**

Google Drive

**Comment by subdavis** [comment]
Please read the troubleshooting guide like it says in the app.

**Comment by UniversalFlamingo** [comment]
> Please read the troubleshooting guide like it says in the app. It will fix this.
> 
> https://github.com/subdavis/Tusk/wiki/Troubleshooting#google-drive-issues

I have did those things before posting, I'm sorry I failed to say so.

I have also tried with a second Google account that has no connections.

On my Chromebook I logged out of all but one Google account & that made no difference. I have not had a chance to try this on Windows.

FWIW - Things _do_ work as expected with Firefox on Windows.

**Comment by baergj** [comment]
I've also been having this issue ever since the 2024.8.2 I eventually convinced Google to let me reconnect the app but then the issue recurred with the .10 update (so maybe this is somehow related to when the extension is updated?).

I've followed the troubleshooting instructions FWIW but I've been unable to reconnect since the .10 update.

**Comment by Dadadah** [comment]
I am also having this issue, I'm using chrome and am unable to use Tusk right now. When I try to access the database in the Tusk UI, Google responds with "App Blocked"

**Comment by subdavis** [comment]
You are all correct.  I made a mistake in the latest release to the chrome web store and caused a permissions regression for chrome.  I did not make this same mistake on the latest release to the  Mozilla store because the permissions are requested in a different way.

Sorry for the confusion, and thank you for reporting this problem.  A fix will be available in 2024.8.12.

**Comment by baergj** [comment]
Confirmed that this is all better in .12 - thank you!

**Comment by Dadadah** [comment]
Confirmed as working for me. Thanks for fixing quickly!

**Comment by UniversalFlamingo** [comment]
Likewise confirmed for both Windows and Chromebook.
Tusk is literally the only option for browser integration on Chromebook, thank you for tracking this down so quickly!
