### ISSUE TITLE
Will not install on Portable Firefox

### ISSUE THREAD

**Issue by rrhobbs** [subdavis/Tusk#56]
## This issue is a 

- [x] bug
- [x] feature
- [x] question

### Please describe the current behavior, and explain why it's bad.
Will not install on Portable Firefox from Extension store

### Please describe how you think it should change.
downloadable

**Comment by subdavis** [comment]
Thanks for opening this issue.

Are you trying to use the Chrome portable download from https://portableapps.com/apps/internet/firefox_portable ?   As this is windows only software and I don't have access to a Windows machine, this may be hard for me to debug.

I also have mixed feelings about how to move forward here, so bear with me.

1. In this early stage of the project, poor reviews can hurt a lot, and so I'm going to do my best to address this issue.
2. It's tough because portableapps.com applications are _not_ officially supported by Mozilla, Google, etc.  and therefore not offically supported by Tusk.  It's sort of like getting a bad review because Tusk doesn't work on Vivaldi or Opera.  Sure, they're Chromium underneath, but Google isn't responsible for them.  If you read the page on https://portableapps.com/apps/internet/google_chrome_portable, the author descibes "Some Settings Locked Per PC", and so I'm going to regard Chrome Portable as a different variant of Chrome that I make no guarantees about.  

The same goes for firefox.  As mentioned in the Known Issues -  https://portableapps.com/support/firefox_portable#known_issues - some extensions will fail.

Thank you for both your rating and your taking the time to open this issue.  I'm going to do my best to figure out what went wrong with the PortableApps variant, but meanwhile, if you could edit your review to reflect your experience with Tusk on an officially supported browser, I would really appreciate it.
