### ISSUE TITLE
database auto unlock fails.

### ISSUE THREAD

**Issue by mistersister** [subdavis/Tusk#73]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
The option to unlock the db for 24h doesnt seem to work. It gets locked several times per day and I have to manually unlock it even though I dont close the browser.

### Please describe how you think it should change.
It should autounlock without the need to manually enter the password.

### Anything else?
Using Chromium Version 63.0.3239.132 (Developer Build) (64-bit) on an up to date Arch Linux box.

**Comment by subdavis** [comment]
Auto-unlock depends on a chrome background page for keeping credentials in memory.  Chrome isn't really specific about when it kills background pages, so even if you leave the browser open, the background page may occasionally be lost, especially if your computer goes to sleep or you're inactive for a while

Can you help me debug this?

* Do you get a browser notification about your credentials being forgotten?  If so, this is a bug.
* Have you tuned Chrome performance any with any of the advanced options flags pages (chrome://flags/) ?

If the answer to both of those questions is no, this will be very hard to track down.  You can probably rest easy knowing that Chrome just killed the background page because it's a quirky little application that does strange things.

**Comment by mistersister** [comment]
Hello,

no, I dont get any notifications on credentials being erased. And I also dont use any modifications on chrome://flags. 

If anything, the only thing I do is start Chromium with the --disk-cache-dir command line argument to move the cache to another drive.
